# Generated by Django 3.1.5 on 2021-12-09 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20211209_2105'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentdata',
            unique_together=set(),
        ),
    ]
